### ISSUE TITLE
Getting Segmentation fault while training on MNLI

### ISSUE THREAD

**Issue by RishabhMaheshwary** [coetaur0/ESIM#11]
==================== Training ESIM model on device: cuda:0 ====================
* Training epoch 1:
Avg. batch proc. time: 0.0299s, loss: 0.8712: 100%|█████████████████████████████████████████████████████████████| 49088/49088 [26:49<00:00, 30.49it/s]
Segmentation fault (core dumped)

**Comment by coetaur0** [comment]
It's a bit difficult to guess what went wrong solely on the basis of this error message. But which version of PyTorch did you use? The model was developed with PyTorch 0.4 (although it worked with version 1.0 when I last tried). Maybe this has something to do with it.
