### ISSUE TITLE
I have run the code for many times, but the test result fails to reach 88, which is only about 87.6. Is there any detail that needs attention

### ISSUE THREAD

**Issue by tangfuping** [coetaur0/ESIM#14]
I have run the code for many times, but the test result fails to reach 88, which is only about 87.6. Is there any detail that needs attention？

**Comment by coetaur0** [comment]
This is odd. Did you use the pretrained model from the *data/checkpoints/SNLI* folder ? If not, it is possible that different executions to train the model produce different weights with varying levels of accuracy. If you train the model multiple times, you should however reach something around 88% on average.
