### ISSUE TITLE
ImportError in train_snli.py

### ISSUE THREAD

**Issue by RottenShow** [coetaur0/ESIM#3]
-sorry, stupid question, found it myself.-

If I try to run train_snli.py, an error occurs:

Traceback (most recent call last):
  File "train_snli.py", line 19, in <module>
    from utils import train, validate
ImportError: cannot import name 'train'

This seems justified, because esim/esim/utils.py do not include train and validate.
Is this call referring to another script? Or what shall be done?

**Comment by Hutommy** [comment]
Hello, genius, I just want to know where is the worddict.pkl when I run 'preprocess_bnli.py --config ...bnli_preprocessing.json'.
File "preprocess_bnli.py", line 73, in preprocess_BNLI_data
    with open(worddict, 'rb') as pkl:
FileNotFoundError: [Errno 2] No such file or directory: '../data/preprocessed/SNLI/worddict.pkl'
