### ISSUE TITLE
No such file or directory: worddict.pkl

### ISSUE THREAD

**Issue by Hutommy** [coetaur0/ESIM#4]
Hello, genius, I just want to know where is the worddict.pkl when I run 'preprocess_bnli.py --config ...bnli_preprocessing.json'.
File "preprocess_bnli.py", line 73, in preprocess_BNLI_data
with open(worddict, 'rb') as pkl:
FileNotFoundError: [Errno 2] No such file or directory: '../data/preprocessed/SNLI/worddict.pkl'

**Comment by coetaur0** [comment]
Hi, as mentioned in the README, before you can preprocess the BNLI data set you need to preprocess SNLI. This will produce a worddict for SNLI which will then re-used in BNLI. The reason for this is that the Breaking NLI data set is only an additional test set for SNLI.

**Comment by Hutommy** [comment]
Ohhhh, thank you very much, I find that,  feeling so stupid for my carelessness.

**Comment by coetaur0** [comment]
No problem, I'm happy to help!
