### ISSUE TITLE
What is the BNLI dataset?

### ISSUE THREAD

**Issue by rzhangpku** [coetaur0/ESIM#6]
What is the Breaking NLI (BNLI) dataset? And where can I download the BNLI dataset? I cannot find the BNLI dataset by searching "Breaking NLI (BNLI)" or "Breaking NLI (BNLI) dataset" in Google.
Thank you very much!

**Comment by coetaur0** [comment]
Hi. You can find the paper about the Breaking NLI dataset at this address: https://arxiv.org/pdf/1805.02266.pdf and download the data here: https://github.com/BIU-NLP/Breaking_NLI.

**Comment by rzhangpku** [comment]
Thanks a lot!
